# Generated by Django 3.0.7 on 2020-06-09 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intrest_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=100)),
                ('Category_Image', models.ImageField(upload_to='')),
                ('Created_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan_Name', models.CharField(max_length=100)),
                ('Plans_Price', models.CharField(max_length=100)),
                ('Plans_Days_Limit', models.CharField(max_length=100)),
                ('Plans_Creates_At', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titel', models.CharField(max_length=100)),
                ('Videos', models.FileField(upload_to='')),
                ('Author_Name', models.CharField(max_length=1000)),
                ('Descriptions', models.TextField(max_length=3000)),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.Intrest_Category')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Users_Name', models.CharField(max_length=100)),
                ('Users_Email', models.CharField(max_length=100, unique=True)),
                ('Users_Password', models.CharField(max_length=100)),
                ('Users_Join_Date', models.DateTimeField(auto_now_add=True)),
                ('Is_User_Active', models.BooleanField(default=True, verbose_name='Is User Active')),
                ('Intrest_Category', models.ManyToManyField(to='Mainapp.Intrest_Category')),
                ('Users_Current_Plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.Plans')),
            ],
        ),
        migrations.CreateModel(
            name='Intrest_Sub_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_Category_Name', models.CharField(max_length=100)),
                ('Sub_Category_Image', models.ImageField(upload_to='')),
                ('Created_date_time', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.Intrest_Category')),
            ],
        ),
    ]
